# Generated by Django 3.1 on 2020-08-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
